# Generated by Django 5.1.6 on 2025-02-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='book_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
