# Generated by Django 5.1.6 on 2025-02-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_alter_transactionmodel_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
