# Generated by Django 5.1.6 on 2025-03-24 08:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_transactionmodel_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='related_borrow',
            field=models.ForeignKey(blank=True, limit_choices_to={'transaction_type': 'borrow'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='Transactions.transactionmodel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
