# Generated by Django 5.1.6 on 2025-02-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0003_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverdueBorrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_id', models.CharField(max_length=255)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_student_count', models.IntegerField(default=0)),
                ('total_book_count', models.IntegerField(default=0)),
                ('total_transaction_count', models.IntegerField(default=0)),
                ('total_borrowed_books', models.IntegerField(default=0)),
                ('total_returned_books', models.IntegerField(default=0)),
                ('overdue_borrowers', models.ManyToManyField(related_name='dashboards', to='Dashboard.overdueborrower')),
            ],
        ),
    ]
