# Generated by Django 5.1.6 on 2025-02-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overdueborrower',
            name='last_email_sent',
        ),
    ]
