# Generated by Django 5.1.6 on 2025-02-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_remove_overdueborrower_last_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='overdueborrower',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
